version: "3.4"

services:
  bouncer:
    image: benzine/bouncer
    build: .
    environment:
      - BOUNCE_SITE_A_DOMAIN="a.example.local"
      - BOUNCE_SITE_A_PORT=80
      - BOUNCE_SITE_A_SERVICE=web-a
      - BOUNCE_SITE_B_DOMAIN="b.example.local"
      - BOUNCE_SITE_B_PORT=80
      - BOUNCE_SITE_B_SERVICE=web-a
    ports:
      - 127.0.99.100:80:80
      - 127.0.99.100:443:443
    depends_on:
      - web-a
      - web-b

  web-a:
    image: benzine/php:nginx
    volumes:
      - ./test/public-web-a:/app/public
    ports:
      - 127.0.99.1:80:80

  web-b:
    image: benzine/php:nginx
    volumes:
      - ./test/public-web-b:/app/public
    ports:
      - 127.0.99.2:80:80
