image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - sed \
     -e "s|gone/marshall|$CI_REGISTRY_IMAGE/marshall|g" \
     -e "s|gone/php:core-|$CI_REGISTRY_IMAGE/php/core:|g" \
     -e "s|gone/php:cli-php|$CI_REGISTRY_IMAGE/php/cli:|g" \
     -e "s|gone/php:nginx-php|$CI_REGISTRY_IMAGE/php/nginx:|g" \
     -e "s|gone/php:apache-php|$CI_REGISTRY_IMAGE/php/apache:|g" \
     -e "s|gone/node:|$CI_REGISTRY_IMAGE/node:|g" \
     -e "s|gone/php:core|$CI_REGISTRY_IMAGE/php/core|g" \
     -e "s|gone/php:cli|$CI_REGISTRY_IMAGE/php/cli|g" \
     -e "s|gone/php:nginx|$CI_REGISTRY_IMAGE/php/nginx|g" \
     -e "s|gone/php:apache|$CI_REGISTRY_IMAGE/php/apache|g" \
     Makefile > Makefile.working

after_script:
  - rm Makefile.working

build:marshall:
  stage: build
  script:
    - make -f Makefile.working build-marshall
  except:
    - master

build:marshall:master:
  stage: build
  script:
    - make -f Makefile.working build-marshall
    - make -f Makefile.working push-marshall
  only:
    - master
