image: gone/mule

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - sh generate_makefile.sh
  - make -f Makefile.working prepare

after_script:
  - rm Makefile.working

build:marshall:
  stage: build
  script:
    - make -f Makefile.working build-marshall
  except:
    - master

build:marshall:master:
  stage: build
  script:
    - make -f Makefile.working build-marshall
    - make -f Makefile.working push-marshall
  only:
    - master
