image: gone/mule

services:
  - docker:dind
    
stages:
  - precursor
  - core
  - derived
  - post

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - sh generate_makefile.sh
  - make -f Makefile.working prepare
  - export GIT_BRANCH=$CI_COMMIT_REF_SLUG
  - printenv | sort

after_script:
  - rm Makefile.working

marshall:
  stage: precursor
  script:
    - make -f Makefile.working build-marshall
  except:
    - master

marshall:master:
  stage: precursor
  script:
    - make -f Makefile.working build-marshall
    - make -f Makefile.working push-marshall
  only:
    - master

php:5.6:
  stage: core
  script:
    - make -f Makefile.working build-php-core-5.6
  except:
    - master

php:5.6:master:
  stage: core
  script:
    - make -f Makefile.working build-php-core-5.6
    - make -f Makefile.working push-core-5.6
  only:
    - master

php:7.0:
  stage: core
  script:
    - make -f Makefile.working build-php-core-7.0
  except:
    - master

php:7.0:master:
  stage: core
  script:
    - make -f Makefile.working build-php-core-7.0
    - make -f Makefile.working push-core-7.0
  only:
    - master

php:7.1:
  stage: core
  script:
    - make -f Makefile.working build-php-core-7.1
  except:
    - master

php:7.1:master:
  stage: core
  script:
    - make -f Makefile.working build-php-core-7.1
    - make -f Makefile.working push-core-7.1
  only:
    - master

php:7.2:
  stage: core
  script:
    - make -f Makefile.working build-php-core-7.2
  except:
    - master

php:7.2:master:
  stage: core
  script:
    - make -f Makefile.working build-php-core-7.2
    - make -f Makefile.working push-core-7.2
  only:
    - master

php:7.3:
  stage: core
  script:
    - make -f Makefile.working build-php-core-7.3
  except:
    - master

php:7.3:master:
  stage: core
  script:
    - make -f Makefile.working build-php-core-7.3
    - make -f Makefile.working push-core-7.3
  only:
    - master

node:8:
  stage: core
  script:
    - make -f Makefile.working build-node-8
  except:
    - master

node:8:master:
  stage: core
  script:
    - make -f Makefile.working build-node-8
    - make -f Makefile.working tag-node-8
    - make -f Makefile.working push-node-8
  only:
    - master

node:10:
  stage: core
  script:
    - make -f Makefile.working build-node-10
  except:
    - master

node:10:master:
  stage: core
  script:
    - make -f Makefile.working build-node-10
    - make -f Makefile.working tag-node-10
    - make -f Makefile.working push-node-10
  only:
    - master
      
node:11:
  stage: core
  script:
    - make -f Makefile.working build-node-11
  except:
    - master

node:11:master:
  stage: core
  script:
    - make -f Makefile.working build-node-11
    - make -f Makefile.working tag-node-11
    - make -f Makefile.working push-node-11
  only:
    - master
      
node:12:
  stage: core
  script:
    - make -f Makefile.working build-node-12
  except:
    - master

node:12:master:
  stage: core
  script:
    - make -f Makefile.working build-node-12
    - make -f Makefile.working tag-node-12
    - make -f Makefile.working push-node-12
  only:
    - master

cli:5.6:
  stage: derived
  script:
    - make -f Makefile.working build-php-cli-5.6
  except:
    - master

cli:5.6:master:
  stage: derived
  script:
    - make -f Makefile.working build-php-cli-5.6
    - make -f Makefile.working push-cli-5.6
  only:
    - master

apache:5.6:
  stage: derived
  script:
    - make -f Makefile.working build-php-apache-5.6
  except:
    - master

apache:5.6:master:
  stage: derived
  script:
    - make -f Makefile.working build-php-apache-5.6
    - make -f Makefile.working push-apache-5.6
  only:
    - master

nginx:5.6:
  stage: derived
  script:
    - make -f Makefile.working build-php-nginx
  except:
    - master

nginx:5.6:master:
  stage: derived
  script:
    - make -f Makefile.working build-php-nginx-5.6
    - make -f Makefile.working push-nginx-5.6
  only:
    - master


cli:7.0:
  stage: derived
  script:
    - make -f Makefile.working build-php-cli-7.0
  except:
    - master

cli:7.0:master:
  stage: derived
  script:
    - make -f Makefile.working build-php-cli-7.0
    - make -f Makefile.working push-cli-7.0
  only:
    - master

apache:7.0:
  stage: derived
  script:
    - make -f Makefile.working build-php-apache-7.0
  except:
    - master

apache:7.0:master:
  stage: derived
  script:
    - make -f Makefile.working build-php-apache-7.0
    - make -f Makefile.working push-apache-7.0
  only:
    - master

nginx:7.0:
  stage: derived
  script:
    - make -f Makefile.working build-php-nginx
  except:
    - master

nginx:7.0:master:
  stage: derived
  script:
    - make -f Makefile.working build-php-nginx-7.0
    - make -f Makefile.working push-nginx-7.0
  only:
    - master


cli:7.1:
  stage: derived
  script:
    - make -f Makefile.working build-php-cli-7.1
  except:
    - master

cli:7.1:master:
  stage: derived
  script:
    - make -f Makefile.working build-php-cli-7.1
    - make -f Makefile.working push-cli-7.1
  only:
    - master

apache:7.1:
  stage: derived
  script:
    - make -f Makefile.working build-php-apache-7.1
  except:
    - master

apache:7.1:master:
  stage: derived
  script:
    - make -f Makefile.working build-php-apache-7.1
    - make -f Makefile.working push-apache-7.1
  only:
    - master

nginx:7.1:
  stage: derived
  script:
    - make -f Makefile.working build-php-nginx
  except:
    - master

nginx:7.1:master:
  stage: derived
  script:
    - make -f Makefile.working build-php-nginx-7.1
    - make -f Makefile.working push-nginx-7.1
  only:
    - master


cli:7.2:
  stage: derived
  script:
    - make -f Makefile.working build-php-cli-7.2
  except:
    - master

cli:7.2:master:
  stage: derived
  script:
    - make -f Makefile.working build-php-cli-7.2
    - make -f Makefile.working push-cli-7.2
  only:
    - master

apache:7.2:
  stage: derived
  script:
    - make -f Makefile.working build-php-apache-7.2
  except:
    - master

apache:7.2:master:
  stage: derived
  script:
    - make -f Makefile.working build-php-apache-7.2
    - make -f Makefile.working push-apache-7.2
  only:
    - master

nginx:7.2:
  stage: derived
  script:
    - make -f Makefile.working build-php-nginx
  except:
    - master

nginx:7.2:master:
  stage: derived
  script:
    - make -f Makefile.working build-php-nginx-7.2
    - make -f Makefile.working push-nginx-7.2
  only:
    - master


cli:7.3:
  stage: derived
  script:
    - make -f Makefile.working build-php-cli-7.3
  except:
    - master

cli:7.3:master:
  stage: derived
  script:
    - make -f Makefile.working build-php-cli-7.3
    - make -f Makefile.working push-cli-7.3
  only:
    - master

apache:7.3:
  stage: derived
  script:
    - make -f Makefile.working build-php-apache-7.3
  except:
    - master

apache:7.3:master:
  stage: derived
  script:
    - make -f Makefile.working build-php-apache-7.3
    - make -f Makefile.working push-apache-7.3
  only:
    - master

nginx:7.3:
  stage: derived
  script:
    - make -f Makefile.working build-php-nginx
  except:
    - master

nginx:7.3:master:
  stage: derived
  script:
    - make -f Makefile.working build-php-nginx-7.3
    - make -f Makefile.working push-nginx-7.3
  only:
    - master

aliases:
  stage: post
  script:
    - make -f Makefile.working aliases