version: '2.4'

services:
  marshall:
    image: gone/marshall
    build:
      context: .
      target: marshall

  node-8:
    image: gone/node:8
    build:
      context: .
      target: nodejs
      args:
        NODE_VERSION: 8.16.0
        YARN_VERSION: 1.15.2
  node-8-onbuild:
    extends:
      service: node-8
    image: gone/node:8-onbuild
    build:
      target: nodejs-onbuild
  node-8-gcc:
    extends:
      service: node-8
    image: gone/node:8-gcc
    build:
      target: nodejs-gcc
  node-8-gcc-onbuild:
    extends:
      service: node-8-gcc
    image: gone/node:8-gcc-onbuild
    build:
      target: nodejs-gcc-onbuild

  node-10:
    image: gone/node:10
    build:
      context: .
      target: nodejs
      args:
        NODE_VERSION: 8.16.0
        YARN_VERSION: 1.15.2
  node-10-onbuild:
    extends:
      service: node-10
    image: gone/node:10-onbuild
    build:
      target: nodejs-onbuild
  node-10-gcc:
    extends:
      service: node-10
    image: gone/node:10-gcc
    build:
      target: nodejs-gcc
  node-10-gcc-onbuild:
    extends:
      service: node-10-gcc
    image: gone/node:10-gcc-onbuild
    build:
      target: nodejs-gcc-onbuild

  node-11:
    image: gone/node:11
    build:
      context: .
      target: nodejs
      args:
        NODE_VERSION: 8.16.0
        YARN_VERSION: 1.15.2
  node-11-onbuild:
    extends:
      service: node-11
    image: gone/node:11-onbuild
    build:
      target: nodejs-onbuild
  node-11-gcc:
    extends:
      service: node-11
    image: gone/node:11-gcc
    build:
      target: nodejs-gcc
  node-11-gcc-onbuild:
    extends:
      service: node-11-gcc
    image: gone/node:11-gcc-onbuild
    build:
      target: nodejs-gcc-onbuild

  node-12:
    image: gone/node:12
    build:
      context: .
      target: nodejs
      args:
        NODE_VERSION: 8.16.0
        YARN_VERSION: 1.15.2
  node-12-onbuild:
    extends:
      service: node-12
    image: gone/node:12-onbuild
    build:
      target: nodejs-onbuild
  node-12-gcc:
    extends:
      service: node-12
    image: gone/node:12-gcc
    build:
      target: nodejs-gcc
  node-12-gcc-onbuild:
    extends:
      service: node-12-gcc
    image: gone/node:12-gcc-onbuild
    build:
      target: nodejs-gcc-onbuild
        
  php-core-56:
    image: gone/php:core-5.6
    build:
      context: .
      target: php-core
      args:
        PHP_VERSION: 5.6
        PHP_PACKAGES:
          mysql-client
          php-apcu
          php-xdebug
          php5.6-bcmath
          php5.6-bz2
          php5.6-cli
          php5.6-curl
          php5.6-gd
          php5.6-imap
          php5.6-intl
          php5.6-json
          php5.6-ldap
          php5.6-mbstring
          php5.6-mcrypt
          php5.6-memcache
          php5.6-memcached
          php5.6-mongodb
          php5.6-mysql
          php5.6-opcache
          php5.6-pgsql
          php5.6-pspell
          php5.6-redis
          php5.6-soap
          php5.6-sqlite
          php5.6-xml
          php5.6-zip
          postgresql-client
        
  php-core-70:
    image: gone/php:core-7.0
    build:
      context: .
      target: php-core
      args:
        PHP_VERSION: 7.0
        PHP_PACKAGES:
          mysql-client
          php-apcu
          php-xdebug
          php7.0-bcmath
          php7.0-bz2
          php7.0-cli
          php7.0-curl
          php7.0-gd
          php7.0-imap
          php7.0-intl
          php7.0-json
          php7.0-ldap
          php7.0-mbstring
          php7.0-mcrypt
          php7.0-memcache
          php7.0-memcached
          php7.0-mongodb
          php7.0-mysql
          php7.0-opcache
          php7.0-pgsql
          php7.0-pspell
          php7.0-redis
          php7.0-soap
          php7.0-sqlite
          php7.0-xml
          php7.0-zip
          postgresql-client
        
  php-core-71:
    image: gone/php:core-7.1
    build:
      context: .
      target: php-core
      args:
        PHP_VERSION: 7.1
        PHP_PACKAGES:
          mysql-client
          php-apcu
          php-xdebug
          php7.1-bcmath
          php7.1-bz2
          php7.1-cli
          php7.1-curl
          php7.1-gd
          php7.1-imap
          php7.1-intl
          php7.1-json
          php7.1-ldap
          php7.1-mbstring
          php7.1-mcrypt
          php7.1-memcache
          php7.1-memcached
          php7.1-mongodb
          php7.1-mysql
          php7.1-opcache
          php7.1-pgsql
          php7.1-pspell
          php7.1-redis
          php7.1-soap
          php7.1-sqlite
          php7.1-xml
          php7.1-zip
          postgresql-client
        
  php-core-72:
    image: gone/php:core-7.2
    build:
      context: .
      target: php-core
      args:
        PHP_VERSION: 7.2
        PHP_PACKAGES:
          mysql-client
          php-apcu
          php-xdebug
          php7.2-bcmath
          php7.2-bz2
          php7.2-cli
          php7.2-curl
          php7.2-gd
          php7.2-imap
          php7.2-intl
          php7.2-json
          php7.2-ldap
          php7.2-mbstring
          php7.2-memcache
          php7.2-memcached
          php7.2-mongodb
          php7.2-mysql
          php7.2-opcache
          php7.2-pgsql
          php7.2-pspell
          php7.2-redis
          php7.2-soap
          php7.2-sqlite
          php7.2-xml
          php7.2-zip
          postgresql-client
  php-core-73:
    image: gone/php:core-7.3
    build:
      context: .
      target: php-core
      args:
        PHP_VERSION: 7.3
        PHP_PACKAGES:
          mysql-client
          php-apcu
          php-xdebug
          php7.3-bcmath
          php7.3-bz2
          php7.3-cli
          php7.3-curl
          php7.3-gd
          php7.3-imap
          php7.3-intl
          php7.3-json
          php7.3-ldap
          php7.3-mbstring
          php7.3-memcache
          php7.3-memcached
          php7.3-mongodb
          php7.3-mysql
          php7.3-opcache
          php7.3-pgsql
          php7.3-pspell
          php7.3-redis
          php7.3-soap
          php7.3-sqlite
          php7.3-xml
          php7.3-zip
          postgresql-client

  php-cli-56:
    extends:
      service: php-core-56
    image: gone/php:cli-5.6
    build:
      context: .
      target: php-cli
  php-cli-56-onbuild:
    extends:
      service: php-core-56
    image: gone/php:cli-5.6-onbuild
    build:
      context: .
      target: php-cli-onbuild 
  php-cli-70:
    extends:
      service: php-core-70
    image: gone/php:cli-7.0
    build:
      context: .
      target: php-cli
  php-cli-70-onbuild:
    extends:
      service: php-core-70
    image: gone/php:cli-7.0-onbuild
    build:
      context: .
      target: php-cli-onbuild
  php-cli-71:
    extends:
      service: php-core-71
    image: gone/php:cli-7.1
    build:
      context: .
      target: php-cli
  php-cli-71-onbuild:
    extends:
      service: php-core-71
    image: gone/php:cli-7.1-onbuild
    build:
      context: .
      target: php-cli-onbuild
  php-cli-72:
    extends:
      service: php-core-72
    image: gone/php:cli-7.2
    build:
      context: .
      target: php-cli
  php-cli-72-onbuild:
    extends:
      service: php-core-72
    image: gone/php:cli-7.2-onbuild
    build:
      context: .
      target: php-cli-onbuild
  php-cli-73:
    extends:
      service: php-core-73
    image: gone/php:cli-7.3
    build:
      context: .
      target: php-cli
  php-cli-73-onbuild:
    extends:
      service: php-core-73
    image: gone/php:cli-7.3-onbuild
    build:
      context: .
      target: php-cli-onbuild

  php-apache-56:
    extends:
      service: php-core-56
    image: gone/php:apache-5.6
    build:
      context: .
      target: php-apache
  php-apache-56-onbuild:
    extends:
      service: php-core-56
    image: gone/php:apache-5.6-onbuild
    build:
      context: .
      target: php-apache-onbuild
  php-apache-70:
    extends:
      service: php-core-70
    image: gone/php:apache-7.0
    build:
      context: .
      target: php-apache
  php-apache-70-onbuild:
    extends:
      service: php-core-70
    image: gone/php:apache-7.0-onbuild
    build:
      context: .
      target: php-apache-onbuild
  php-apache-71:
    extends:
      service: php-core-71
    image: gone/php:apache-7.1
    build:
      context: .
      target: php-apache
  php-apache-71-onbuild:
    extends:
      service: php-core-71
    image: gone/php:apache-7.1-onbuild
    build:
      context: .
      target: php-apache-onbuild
  php-apache-72:
    extends:
      service: php-core-72
    image: gone/php:apache-7.2
    build:
      context: .
      target: php-apache
  php-apache-72-onbuild:
    extends:
      service: php-core-72
    image: gone/php:apache-7.2-onbuild
    build:
      context: .
      target: php-apache-onbuild
  php-apache-73:
    extends:
      service: php-core-73
    image: gone/php:apache-7.3
    build:
      context: .
      target: php-apache
  php-apache-73-onbuild:
    extends:
      service: php-core-73
    image: gone/php:apache-7.3-onbuild
    build:
      context: .
      target: php-apache-onbuild

  php-nginx-56:
    extends:
      service: php-core-56
    image: gone/php:nginx-5.6
    build:
      context: .
      target: php-nginx
  php-nginx-56-onbuild:
    extends:
      service: php-core-56
    image: gone/php:nginx-5.6-onbuild
    build:
      context: .
      target: php-nginx-onbuild
  php-nginx-70:
    extends:
      service: php-core-70
    image: gone/php:nginx-7.0
    build:
      context: .
      target: php-nginx
  php-nginx-70-onbuild:
    extends:
      service: php-core-70
    image: gone/php:nginx-7.0-onbuild
    build:
      context: .
      target: php-nginx-onbuild
  php-nginx-71:
    extends:
      service: php-core-71
    image: gone/php:nginx-7.1
    build:
      context: .
      target: php-nginx
  php-nginx-71-onbuild:
    extends:
      service: php-core-71
    image: gone/php:nginx-7.1-onbuild
    build:
      context: .
      target: php-nginx-onbuild
  php-nginx-72:
    extends:
      service: php-core-72
    image: gone/php:nginx-7.2
    build:
      context: .
      target: php-nginx
  php-nginx-72-onbuild:
    extends:
      service: php-core-72
    image: gone/php:nginx-7.2-onbuild
    build:
      context: .
      target: php-nginx-onbuild
  php-nginx-73:
    extends:
      service: php-core-73
    image: gone/php:nginx-7.3
    build:
      context: .
      target: php-nginx
  php-nginx-73-onbuild:
    extends:
      service: php-core-73
    image: gone/php:nginx-7.3-onbuild
    build:
      context: .
      target: php-nginx-onbuild

  node-latest:
    extends:
      service: node-12
    image: gone/node:latest
  node-onbuild-latest:
    extends:
      service: node-12
    image: gone/node:onbuild

  php-cli-latest:
    extends:
      service: php-cli-73
    image: gone/php:cli
  php-cli-onbuild-latest:
    extends:
      service: php-cli-73-onbuild
    image: gone/php:cli-onbuild
    
  php-apache-latest:
    extends:
      service: php-apache-73
    image: gone/php:apache
  php-apache-onbuild-latest:
    extends:
      service: php-apache-73-onbuild
    image: gone/php:apache-onbuild

  php-nginx-latest:
    extends:
      service: php-nginx-73
    image: gone/php:nginx
  php-nginx-onbuild-latest:
    extends:
      service: php-nginx-73-onbuild
    image: gone/php:nginx-onbuild