version: "3.4"

services:
  redis:
    image: redis
    ports:
      - 127.0.0.30:6379:6379
  agent:
    image: matthewbaggett/swarm-agent:agent
    build:
      context: .
      target: swarm-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- /proc/meminfo:/proc/meminfo:ro
      - ./:/app
    command: [/app/agent]
    environment:
      - HOSTNAME=exploding-bolts
      - REDIS_HOST=redis
      - MINIMUM_UPDATE_INTERVAL=10
    depends_on:
      - redis
  stats:
    image: matthewbaggett/swarm-agent:stats
    build:
      context: .
      target: swarm-stats
    volumes:
      - ./:/app
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    ports:
      - 127.0.0.30:80:80
