version: "3.7"
services:
  mongodb:
    build: .
    image: ghcr.io/benzine-framework/mongodb:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=testdb
