name: Build Nginx + LetsEncrypt Bouncer

on:
  push:
    paths:
      - bouncer
  workflow_run:
    workflows:
      - Build PHP Flavours
    branches: [ 'master', 'feature/**' ]
    types:
      - completed

jobs:
  wordpress-build:
    name: "Bake Bouncer Container"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/build-push-action@v2
        name: Build & Push
        with:
          context: bouncer
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: benzine/bouncer
