name: Build Nginx + LetsEncrypt Bouncer

on:
  push:
    paths:
      - 'bouncer/**'
  pull_request:
    branches:
      - '!dependabot/**'
  workflow_run:
    workflows:
      - Build PHP Flavours
    branches: [ 'master', 'feature/**' ]
    types:
      - completed
  workflow_dispatch:

jobs:
  bouncer-build:
    name: "Bake Bouncer Container"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/login-action@v2
        name: Login to GHCR
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - uses: docker/build-push-action@v3
        name: Build & Push
        with:
          context: bouncer
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          target: bouncer
          build-args: |
            GIT_SHA=${{ github.sha }}
          tags: |
            benzine/bouncer
            ghcr.io/benzine-framework/bouncer:latest
