name: Marshall

on:
  push:
    paths:
      - 'marshall/**'
      - 'Dockerfile'
      - '.dockerignore'
  schedule:
    - cron: '0 4 * * TUE'

jobs:
  Marshall:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to registries
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p  ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Setup
      run: |
        git rev-parse --short HEAD > marshall/marshall_version
        date '+%Y-%m-%d %H:%M:%S' > marshall/marshall_build_date
        hostname > marshall/marshall_build_host
    - name: Build Image
      run: docker build -t marshall --target=marshall .
    - name: Tag Image
      run: |
        docker tag marshall gone/marshall:latest
    - name: Publish Image to Registries
      run: |
        docker push gone/marshall:latest
