name: Build

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: build-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  qc:
    name: Trunk
    uses: ./.github/workflows/trunk.check.yml
    secrets: inherit
    permissions: write-all

  marshall:
    needs: qc
    name: Marshall
    uses: ./.github/workflows/marshall.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  php:
    needs: marshall
    name: PHP Core
    uses: ./.github/workflows/php.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  laravel:
    needs: php
    name: PHP Vanity Tags
    uses: ./.github/workflows/laravel.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  bouncer:
    needs: php
    name: Nginx Load Balancer (Bouncer)
    uses: ./.github/workflows/bouncer.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  mitm-proxy:
    needs: qc
    name: Man-in-the-middle proxy
    uses: ./.github/workflows/mitm-proxy.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  mqtt:
    needs: qc
    name: MQTT
    uses: ./.github/workflows/mqtt.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  mysql-proxy:
    needs: qc
    name: MySQL Proxy
    uses: ./.github/workflows/mysql-proxy.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  node:
    needs: qc
    name: Node
    uses: ./.github/workflows/node.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  redis:
    needs: qc
    name: Redis
    uses: ./.github/workflows/redis.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  swarm-monitor:
    needs: php
    name: Swarm Monitor
    uses: ./.github/workflows/swarm-monitor.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  wordpress:
    needs: php
    name: Wordpress
    uses: ./.github/workflows/wordpress.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  scout:
    strategy:
      fail-fast: false
      matrix:
        image:
          - "ghcr.io/benzine-framework/php:cli-8.3"
    name: Helix Docker Scout
    permissions:
      contents: read # For repo checkout
    needs:
      - bouncer
      - laravel
      - marshall
      - mitm-proxy
      - mqtt
      - mysql-proxy
      - node
      - php
      - redis
      - swarm-monitor
      - wordpress
    runs-on: ubuntu-latest
    steps:
      - name: "Docker Scout"
        uses: ./.github/workflows/scout.yml
        with:
          scout: ${{ matrix.image }}
