name: Marshall arm64v8

on:
  push:
    paths:
      - 'marshall/**'
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/build-arm64v8-marshall.yml'
      - '.github/workflows/lint-dockerfiles.yml'
  schedule:
    - cron: '0 4 * * TUE'

jobs:
  Marshall:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to registries
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p  ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker login docker.pkg.github.com -u ${{ secrets.DOCKER_GITHUB_USERNAME }} -p  ${{ secrets.DOCKER_GITHUB_PASSWORD }}
    - name: Setup
      run: |
        git rev-parse --short HEAD > marshall/marshall-arm64v8_version
        date '+%Y-%m-%d %H:%M:%S' > marshall/marshall-arm64v8_build_date
        hostname > marshall/marshall-arm64v8_build_host
    - name: Build Image
      run: docker build -t marshall --target=marshall .
    - name: Tag Image
      run: |
        docker tag marshall gone/marshall-arm64v8:latest
        docker tag marshall docker.pkg.github.com/goneio/base-image/marshall-arm64v8:latest
    - name: Publish Image to Registries
      run: |
        docker push gone/marshall-arm64v8:latest
        docker push docker.pkg.github.com/goneio/base-image/marshall-arm64v8:latest
