name: DynamoDB

permissions:
  contents: read
  packages: write

on:
  workflow_call:
  workflow_dispatch:

jobs:
  dynamodb-build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: dynamodb

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v2

      - name: "Setup: Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: matthewbaggett
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: "Setup: Login to GHCR"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: matthewbaggett
          password: ${{ secrets.GHCR_PASSWORD }}

      - uses: docker/build-push-action@v5
        name: Build & Push
        with:
          context: dynamodb
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: |
            gone/dynamodb
            benzine/dynamodb
            ghcr.io/benzine-framework/dynamodb
