name: Build Laravel Container

on:
  push:
    paths:
      - 'laravel/**'
  pull_request:
    branches:
      - '!dependabot/**'
  workflow_run:
    workflows:
      - Build PHP Vanity Tags
    branches: [ 'master', 'feature/**' ]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    name: "Bake Laravel Container"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
#      - uses: docker/login-action@v2
#        name: Login to Github Container Registry
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        name: Build & Push
        with:
          context: laravel
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: |
#            ghcr.io/benzine-framework/laravel
            matthewbaggett/laravel
