name: Lint Docker Files

on:
  schedule:
    - cron: '0 4 * * TUE'
  workflow_dispatch:


jobs:
  lint:
    name: Lint Docker Files
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        dockerfile:
          - marshall/Dockerfile
          - php/Dockerfile.Core
          - php/Dockerfile.Flavours
          - node/Dockerfile
          - mariadb/Dockerfile
          - redis/Dockerfile
          - octoprint/Dockerfile
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: ${{ matrix.dockerfile }}