name: MariaDB w/Healthcheck

permissions:
  contents: read
  packages: write

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - mariadb/**
      - .github/workflows/mariadb.yml

env:
  should_push: ${{ github.ref == 'refs/heads/main' }}

jobs:
  mariadb-build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - latest
          - 11
          - 11.2
          - 11.1
          - 11.0
          - 10.11
          - "10.10"
          - 10.6
          - 10.5
          - 10.4

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - name: "Setup: Login to Docker Hub"
        if: ${{ env.should_push }}
        uses: docker/login-action@v3
        with:
          username: matthewbaggett
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: "Setup: Login to GHCR"
        if: ${{ env.should_push }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: matthewbaggett
          password: ${{ secrets.GHCR_PASSWORD }}

      - uses: docker/build-push-action@v4
        name: Build & Push
        with:
          context: mariadb
          platforms: ${{ env.ACT && 'linux/amd64' || 'linux/amd64,linux/arm64' }}
          pull: true
          push: ${{ env.should_push }}
          tags: |
            benzine/mariadb:${{ matrix.version }}
            ghcr.io/benzine-framework/mariadb:${{ matrix.version }}
          build-contexts: |
            mariadb:injected-version=docker-image://mariadb:${{ matrix.version }}
