name: Build Marshall

on:
  push:
    paths:
      - 'marshall/**'
  pull_request:
    branches:
      - '!dependabot/**'
  workflow_run:
    workflows:
      - Lint Docker Files
    branches: [ 'master', 'feature/**' ]
    types:
      - completed
  workflow_dispatch:

jobs:

  marshall-build:
    name: "Build Marshall"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Setup Marshall
        run: |
          git rev-parse --short HEAD > marshall/marshall_version
          date '+%Y-%m-%d %H:%M:%S' > marshall/marshall_build_date
          hostname > marshall/marshall_build_host
      - uses: docker/build-push-action@v3
        name: Build & Push
        with:
          context: marshall
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: |
            benzine/marshall:latest
