name: Build Marshall

on:
  push:
    paths:
      - marshall
  workflow_run:
    workflows:
      - Lint Docker Files
    branches: [master]
    types:
      - completed

jobs:

  build:
    name: "Build Marshall"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/login-action@v1
        name: Login to Github Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Setup Marshall
        run: |
          git rev-parse --short HEAD > marshall/marshall_version
          date '+%Y-%m-%d %H:%M:%S' > marshall/marshall_build_date
          hostname > marshall/marshall_build_host
      - uses: docker/build-push-action@v2
        name: Build & Push
        with:
          context: marshall
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: |
            benzine/marshall:latest
            gone/marshall:latest
