name: Build Marshall

permissions: read-all

on:
  push:
    paths:
      - "marshall/**"
  pull_request:
    branches:
      - "!dependabot/**"
  workflow_run:
    workflows:
      - Lint Docker Files
    branches: ["master", "feature/**"]
    types:
      - completed
  workflow_dispatch:

jobs:
  marshall-build:
    name: "Build Marshall"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu:
          - focal
          - jammy
          - lunar
          - mantic
          - noble
          - devel
          - rolling
          - latest
    steps:
      - name: "Build: Prepare Environment Variables"
        id: environment
        run: |
          {
            echo "datetime=$(date +'%Y-%m-%d %H:%M:%S')"
            echo "date=$(date +'%Y-%m-%d')"
            echo "time=$(date +'%H:%M:%S')"
            echo "container_build_datetime=$(date -u +'%Y-%m-%dT%H:%M:%S.%3NZ')"
            echo "marshall_version=$(git rev-parse --short HEAD)"
            echo "marshall_build_date=$(date '+%Y-%m-%d %H:%M:%S')"
            echo "marshall_build_host=$(hostname)"
          } >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            marshall

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - name: "Setup: Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: "Setup: Login to GHCR"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - uses: docker/build-push-action@v5
        name: Build & Push
        with:
          context: marshall
          platforms: ${{ !env.ACT && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          pull: true
          push: ${{ !env.ACT && true || false }}
          tags: |
            ghcr.io/benzine-framework/marshall:${{ matrix.ubuntu }}
            benzine/marshall:${{ matrix.ubuntu }}
          build-args: |
            MARSHALL_VERSION=${{ steps.environment.outputs.marshall_version }}
            MARSHALL_BUILD_DATE=${{ steps.environment.outputs.marshall_build_date }}
            MARSHALL_BUILD_HOST=${{ steps.environment.outputs.marshall_build_host }}
          cache-from: ${{ !env.ACT && 'type=gha' || 'type=local,src=/tmp' }}
          cache-to: ${{ !env.ACT && 'type=gha,mode=max' || 'type=local,dest=/tmp' }}
          build-contexts: |
            ubuntu=docker-image://ubuntu:${{ matrix.ubuntu }}

  marshall-tag-latest:
    name: Tag latest marshall
    runs-on: ubuntu-latest
    needs:
      - marshall-build
    env:
      latest-stable-version: "focal"
      base_tag: "ghcr.io/benzine-framework/marshall"
    strategy:
      fail-fast: false
      matrix:
        output_tag:
          - "benzine/php"
          - "gone/php"
          - "ghcr.io/benzine-framework/php"
    steps:
      - name: "Setup: Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: "Setup: Login to GHCR"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: "Retag ${{ env.base_tag }}:${{ env.latest-stable-version }} to ${{ matrix.output_tag }}:latest"
        if: ${{ github.ref == 'refs/heads/main' }}
        shell: bash
        run: |
          docker pull ${{ env.base_tag }}:${{ env.latest-stable-version }}
          docker tag ${{ env.base_tag }}:${{ env.latest-stable-version }} ${{ matrix.output_tag }}:latest
          docker push ${{ matrix.output_tag }}:latest
