name: Build MQTT

permissions: read-all

on:
  push:
    paths:
      - "mqtt/**"
  pull_request:
    branches:
      - "!dependabot/**"
  workflow_run:
    workflows:
      - Lint Docker Files
    branches: ["master", "feature/**"]
    types:
      - completed
  workflow_dispatch:

jobs:
  mqtt-build:
    name: "MQTT"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/build-push-action@v3
        name: Build & Push
        with:
          context: mqtt
          platforms: linux/amd64,linux/arm64
          pull: true
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            benzine/mqtt
