name: Build MQTT

on:
  push:
    paths:
      - 'mqtt/**'
  pull_request:
    branches:
      - '!dependabot/**'
  workflow_run:
    workflows:
      - Lint Docker Files
    branches: [ 'master', 'feature/**' ]
    types:
      - completed

jobs:
  MQTT-build:
    name: "MQTT"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/login-action@v1
        name: Login to Github Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - uses: docker/build-push-action@v2
        name: Build & Push
        with:
          context: mqtt
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: |
            benzine/mqtt
            ghcr.io/benzine-framework/mqtt
