name: Build Octoprint

permissions:
  contents: read
  packages: write

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "octoprint/**"
      - ".github/workflows/octoprint.yml"

env:
  should_push: ${{ github.ref == 'refs/heads/main' }}

jobs:
  octoprint-build:
    name: "Bake Octoprint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v3
        name: Login to Docker Hub
        with:
          username: matthewbaggett
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - uses: docker/build-push-action@v3
        name: Build Octoprint
        with:
          context: octoprint
          target: octoprint
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          pull: true
          push: ${{ env.should_push && !env.ACT }}
          tags: matthewbaggett/octoprint:latest

  octoprint-mjpg-build:
    name: "Bake Octoprint for yuvu cameras"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v2
      - name: "Setup: Login to Docker Hub"
        if: ${{ env.should_push }}
        uses: docker/login-action@v3
        with:
          username: matthewbaggett
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: "Setup: Login to GHCR"
        if: ${{ env.should_push }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: matthewbaggett
          password: ${{ secrets.GHCR_PASSWORD }}
      - uses: docker/build-push-action@v3
        name: Build Octoprint MJPG Streamer Variant
        with:
          context: octoprint
          target: octoprint-mjpg-streamer
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          pull: true
          push: ${{ env.should_push && !env.ACT }}
          tags: matthewbaggett/octoprint:mjpg-streamer-yu12
