name: Build PHP Vanity Tags

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Build PHP Flavours
    branches: [ 'master', 'feature/**' ]
    types:
      - completed

jobs:
  php-vanity-tags:
    name: Vanity Tags
    runs-on: ubuntu-latest
    env:
      latest-stable-version: "8.2"
    strategy:
      fail-fast: false
      matrix:
        variant:
          - cli
          - nginx
          - apache
    steps:
      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Retag benzine/php:${{ matrix.variant }}-${{ env.latest-stable-version }} to benzine/php:${{ matrix.variant }}
        run: |
          docker pull benzine/php:${{ matrix.variant }}-${{ env.latest-stable-version }}
          docker tag benzine/php:${{ matrix.variant }}-${{ env.latest-stable-version }} benzine/php:${{ matrix.variant }}
          docker push benzine/php:${{ matrix.variant }}
          docker tag benzine/php:${{ matrix.variant }}-${{ env.latest-stable-version }} gone/php:${{ matrix.variant }}-${{ env.latest-stable-version }}
          docker push gone/php:${{ matrix.variant }}-${{ env.latest-stable-version }}
          docker tag benzine/php:${{ matrix.variant }}-${{ env.latest-stable-version }} gone/php:${{ matrix.variant }}
          docker push gone/php:${{ matrix.variant }}
