name: PHP CLI

on: [push]

jobs:
  PHP_56:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to registries
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p  ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker login docker.pkg.github.com -u ${{ secrets.DOCKER_GITHUB_USERNAME }} -p  ${{ secrets.DOCKER_GITHUB_PASSWORD }}
      - name: Setup
        run: |
          git rev-parse --short HEAD > marshall/marshall_version
          date +%Y-%m-%d %H:%M:%S > marshall/marshall_build_date
          hostname > marshall/marshall_build_host
      - name: Build Image
        run: docker build -t gone/php:cli-5.6 --target=php-cli --build-arg "PHP_VERSION=5.6" --build-arg "PHP_PACKAGES=$(PHP_PACKAGES_56)" .
        env:
          PHP_PACKAGES_56: mysql-client php-apcu php-xdebug php5.6-bcmath php5.6-bz2 php5.6-cli php5.6-curl php5.6-gd php5.6-imap php5.6-intl php5.6-json php5.6-ldap php5.6-mbstring php5.6-mcrypt php5.6-memcache php5.6-memcached php5.6-mongodb php5.6-mysql php5.6-opcache php5.6-pgsql php5.6-pspell php5.6-redis php5.6-soap php5.6-sqlite php5.6-xml php5.6-zip postgresql-client
      - name: Tag Image
        run: |
          docker tag gone/php:cli-5.6 docker.pkg.github.com/goneio/base-image/php:cli-5.6
      - name: Publish Image to Registries
        run: |
          docker push gone/php:cli-5.6
          docker push gone/php:cli-5.6 docker.pkg.github.com/goneio/base-image/php:cli-5.6
