name: Code Quality Check (Docker Scout)

on:
  workflow_call:
    inputs:
      image:
        description: "The image to check"
        required: true
        type: string

jobs:
  docker-scout:
    runs-on: self-hosted
    steps:
      - name: "Login to Github Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Login to Docker Hub Registry"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: "Docker Scout"
        uses: docker/scout-action@v1.4.1
        with:
          image: ${{ github.event.inputs.image }}
          command: cves,recommendations,compare
          platform: linux/amd64
          write-comment: true
