name: Code Quality Check (Docker Scout)

on:
  workflow_call:
    inputs:
      image:
        description: "The image to check"
        required: true
        type: string

permissions:
  contents: read
  checks: write
  issues: write

jobs:
  docker-scout:
    runs-on: self-hosted
    steps:
      - name: "Setup: Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: matthewbaggett
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: "Setup: Login to GHCR"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: matthewbaggett
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: "Docker Scout"
        uses: docker/scout-action@v1.4.1
        with:
          image: ${{ github.event.inputs.image }}
          command: cves,recommendations,compare
          platform: linux/amd64
          write-comment: true
