name: Build

on:
  push:
    paths:
      - 'swarm-monitor/**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Bake
        working-directory: swarm-monitor
        run: docker buildx bake --push

