name: Build Wordpress Container

permissions:
  contents: read
  packages: write

on:
  workflow_call:
  workflow_dispatch:

env:
  should_push: ${{ github.ref == 'refs/heads/main' }}

jobs:
  wordpress-build:
    name: "Bake Wordpress Container"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - name: "Setup: Login to Docker Hub"
        if: ${{ env.should_push }}
        uses: docker/login-action@v3
        with:
          username: matthewbaggett
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: "Setup: Login to GHCR"
        if: ${{ env.should_push }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: matthewbaggett
          password: ${{ secrets.GHCR_PASSWORD }}

      - uses: docker/build-push-action@v3
        name: Build & Push
        with:
          context: wordpress
          platforms: linux/amd64,linux/arm64
          pull: true
          push: ${{ env.should_push && !env.ACT }}
          tags: |
            matthewbaggett/wordpress
          build-contexts: |
            php:nginx=docker-image://ghcr.io/benzine-framework/php:nginx-8.2
